AboutとCoursesの作成
ryotaot/frontend-basic-site pull request #2
Opened 2024-06-02 09:17 UTC by ryotaot

2024-06-08 14:40 UTC, JunPlayGround requested changes

2024-06-08 14:40 UTC, JunPlayGround commented on index.html
> +        <div class="courses-block-container"></div>
この```div```は何のために配置していますか？
不要だと思います

2024-06-08 14:40 UTC, JunPlayGround commented on index.html
> +    <section id="courses" class="courses">
course部分の構造は今見る感じでは以下のような感じになってそうですが
![1](https://github.com/ryotaot/frontend-basic-site/assets/132260289/544cb2b2-8e41-451c-8a23-47f28991c9d1)
この構造だと、画面幅が狭くなった際に一番下のボタンがはみ出てしまいます
手本を見た際の構造は以下のようになってます
![2](https://github.com/ryotaot/frontend-basic-site/assets/132260289/9b1c0880-ec9d-465a-9060-3304b98cc1a8)
手本サイトを検証ツールで確認してみてください

2024-06-10 13:40 UTC, ryotaot commented on index.html
> +    <section id="courses" class="courses">
いろいろ試行錯誤しても画面幅が狭くなった際に一番下のボタンがはみ出てしまいます。
widthを100%に設定してもはみ出してしまうのですがどうしたらよいでしょうか。

2024-06-12 05:20 UTC, NyoRyorN requested changes

2024-06-12 05:20 UTC, NyoRyorN commented on index.html
> +        <a class="big-button courses-big-button" href="course">
ここから始まる```<a>```要素を上の```div```要素```class=courses-container```のブロック内に入れると解決すると思います

2024-06-12 05:20 UTC, NyoRyorN commented
あと、```div```要素が一つ多いような気がします

2024-06-12 06:15 UTC, ryotaot commented
ありがとうございます。
修正しました。

2024-06-17 12:01 UTC, ssshun3 commented on img/live-music-gb4ff60bb8_1920 1.png
live.pngファイルを使用しましょう。

2024-06-17 12:01 UTC, ssshun3 commented on index.html
> +              src="./img/live-music-gb4ff60bb8_1920 1.png"
live.pngファイルを使用しましょう。

2024-06-17 12:01 UTC, ssshun3 commented on style.css
> +  padding: 10px 40px;
paddingの値をfigmaと見比べてみましょう

2024-06-17 15:36 UTC, ryotaot commented on style.css
> +  padding: 10px 40px;
コメントありがとうございます。修正いたしましたので確認お願いします。

2024-06-18 08:30 UTC, ssshun3 commented on img/live-music-gb4ff60bb8_1920 1.png
このファイルは削除しましょう。

2024-06-18 08:42 UTC, ryotaot commented
訂正しました。よろしくお願いします。

2024-06-18 08:43 UTC, ssshun3 approved these changes

2024-06-18 08:43 UTC, merged