chapter3
ryotaot/frontend-basic-site pull request #3
Opened 2024-06-26 13:34 UTC by ryotaot

2024-06-26 15:22 UTC, Riku-Obata requested changes

2024-06-26 15:22 UTC, Riku-Obata commented on index.html
> +        <f<div class="application-input-container">
```suggestion
        <form style="width: inherit">
         <div class="application-input-container">
```
<f となっているのはタイピングミスかな...？
「width: inherit」は親要素の内容を子要素に継承してくれる便利なCSSです！

以下参考サイトです
[https://developer.mozilla.org/ja/docs/Web/CSS/inherit](url)
[https://web-camp.io/magazine/archives/104553](url)

2024-06-27 01:52 UTC, ryotaot commented on index.html
> +        <f<div class="application-input-container">
コメントありがとうございます。 
<form style="width: inherit">を打ち込んでも画面幅が変わりませんでした。

2024-06-27 01:52 UTC, ryotaot commented
コメントありがとうございます。

を打ち込んでも画面幅が変わりませんでした。

2024-06-27 15:11 UTC, Riku-Obata reviewed
application-input-containerに「display: block;」 を用いると、SP版のような名前とフォームが縦方向になります！が、レスポンシブ対応がうまくいかないようです。

2024-06-27 15:11 UTC, Riku-Obata commented on style.css
> +}
このclassがHTMLの方で見つからないのですが、＜form＞タグの中にあったものでしょうか？

2024-06-27 15:11 UTC, Riku-Obata commented on style.css
> +}
478～483行目と同じようなCSSが使われています

2024-08-24 08:47 UTC, ryotaot commented on style.css
> +}
見落としていました。ありがとうございます。

2024-08-24 17:10 UTC, JunPlayGround requested changes
HTMLファイル内で使用していないクラス名をCSS内で新たに宣言してもサイト上には反映されないので気を付けてください（対応するクラスがないため）

また、自分のサイトと手本のサイトを見比べてある程度近い見た目になったなと思ってからPR出していただけるとありがたいです。

2024-08-24 17:10 UTC, JunPlayGround commented on index.html
> +      <div class="application-container new-container">
class名には基本的に空白はいれない方がいいかもです
css内で参照する際に少し面倒なので

2024-08-24 17:10 UTC, JunPlayGround commented on style.css
> +}
.application-formクラスが見当たらないように思います
おそらく名前のついていない`<form>`タグのところかなとは思いますが

2024-08-24 17:10 UTC, JunPlayGround commented on index.html
> +      <div class="application-container new-container">
あと、手本と見比べた時に説明文とフォーム入力のところと送信ボタンの間隔がおかしくなっているので確認お願いします
この`<div>`クラスにflexまたはgridを利用してgapで幅調整することをお勧めします。

2024-08-24 17:10 UTC, JunPlayGround commented on index.html
> +        <h2 class="application-section-head">Let't Try!</h2>
Let's Tryですね
誤植だと思われます

2024-08-24 17:10 UTC, JunPlayGround commented on style.css
> +.application-section-head {
ここでpaddingは不要だと思います
paddingを適用して行間の調整をしようとしたと思われますが、上述のようにgapで調節するか、このクラスの要素の下側のみにpaddingを設定する方法が考えられます。

2024-09-09 12:48 UTC, ssshun3 commented on style.css
> +  padding: 80px 0px;
```suggestion
  padding: 0px;
```

2024-09-09 12:48 UTC, ssshun3 approved these changes

2024-09-09 23:28 UTC, merged